build:
  image: default-bionic
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override: [php-scrutinizer-run]
    coverage:
      tests:
        override:
          - command: php vendor/bin/phpunit --coverage-text --coverage-clover=build/coverage/coverage.clover
            coverage:
              file: build/coverage/coverage.clover
              format: clover

filter:
  excluded_paths: [tests/*]

checks:
  php:
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true