language: php
php:
  - 8.2
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

script:
    - vendor/bin/phpcs --standard=psr12 src/
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
before_script:
  - composer self-update
  - composer install --no-interaction --verbose
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover