language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 8.0
  - 8.1
  - 8.2
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

script: phpunit ./tests
before_script:
  - composer self-update
  - composer install --no-interaction --verbose